<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Movie;
use Illuminate\Support\Facades\DB;


class MovieSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('movies')->truncate(); /////clears old data so duplicates dont show up everytime i seed

        Movie::insert([
            [
                'title' => 'Inception',
                'description' => 'A thief who steals corporate secrets through dream-sharing.',
                'poster_url' => 'https://m.media-amazon.com/images/I/81p+xe8cbnL._AC_SL1500_.jpg',
                'genre' => 'Sci-Fi',
                'release_year' => 2010,
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Godfather',
                'description' => 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
                'poster_url' => 'https://m.media-amazon.com/images/I/51rOnIjLqzL._AC_.jpg',
                'genre' => 'Crime',
                'release_year' => 1972,
                'director' => 'Francis Ford Coppola',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spirited Away',
                'description' => 'A young girl enters a world of spirits to save her parents.',
                'poster_url' => 'https://media.posterlounge.com/img/products/770000/762649/762649_poster.jpg',
                'genre' => 'Fantasy',
                'release_year' => 2001,
                'director' => 'Hayao Miyazaki',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Matrix',
                'description' => 'A computer hacker learns about the true nature of his reality.',
                'poster_url' => 'https://m.media-amazon.com/images/I/51EG732BV3L.jpg',
                'genre' => 'Sci-Fi',
                'release_year' => 1999,
                'director' => 'The Wachowskis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pulp Fiction',
                'description' => 'The lives of two mob hitmen, a boxer, and others intertwine.',
                'poster_url' => 'https://m.media-amazon.com/images/I/71c05lTE03L._AC_SY679_.jpg',
                'genre' => 'Crime',
                'release_year' => 1994,
                'director' => 'Quentin Tarantino',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Dark Knight',
                'description' => 'Batman must accept one of the greatest psychological and physical tests.',
                'poster_url' => 'https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg',
                'genre' => 'Action',
                'release_year' => 2008,
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            
            [
                'title' => 'Fight Club',
                'description' => 'An insomniac and a soap maker form an underground club.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLw1e05_zatEU0fSuVtS_iYOP7IU25Dj_51s7VReAJmmnOkyjuxtBm_UCL8XQagX2Q5dM&usqp=CAU',
                'genre' => 'Drama',
                'release_year' => 1999,
                'director' => 'David Fincher',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forrest Gump',
                'description' => 'The life journey of a simple man with a big heart.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN_76EybIyj6iIRPGoLg-VPRDJLX74ydCKbQ&s',
                'genre' => 'Drama',
                'release_year' => 1994,
                'director' => 'Robert Zemeckis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Interstellar',
                'description' => 'A team travels through a wormhole to ensure humanity’s survival.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK6tdN2LCV5E1ktnQu82L6m4JX8kP4UwnLJQ&s',
                'genre' => 'Sci-Fi',
                'release_year' => 2014,
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shawshank Redemption',
                'description' => 'Two imprisoned men bond over years, finding redemption.',
                'poster_url' => 'https://m.media-amazon.com/images/I/519NBNHX5BL._AC_.jpg',
                'genre' => 'Drama',
                'release_year' => 1994,
                'director' => 'Frank Darabont',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lord of the Rings: The Fellowship of the Ring',
                'description' => 'A meek hobbit begins a journey to destroy a powerful ring.',
                'poster_url' => 'https://m.media-amazon.com/images/I/51Qvs9i5a+L._AC_.jpg',
                'genre' => 'Fantasy',
                'release_year' => 2001,
                'director' => 'Peter Jackson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lion King',
                'description' => 'A lion cub’s journey to adulthood and acceptance.',
                'poster_url' => 'https://rukminim2.flixcart.com/image/850/1000/kyvvtzk0/poster/j/v/t/medium-the-lion-king-limited-matte-finish-poster-urbanprint5711-original-imagbygdzhgshzmz.jpeg?q=90&crop=false',
                'genre' => 'Animation',
                'release_year' => 1994,
                'director' => 'Roger Allers & Rob Minkoff',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Parasite',
                'description' => 'Greed and class discrimination threaten the relationship between families.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe87QDvtosKzPeZqu0Aks547uXOG8hXlqypw&s',
                'genre' => 'Thriller',
                'release_year' => 2019,
                'director' => 'Bong Joon-ho',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Joker',
                'description' => 'A mentally troubled comedian embarks on a downward spiral.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROBJqux5xMDPJ_34mm2FQQePOKfTV9yWpmOA&s',
                'genre' => 'Crime',
                'release_year' => 2019,
                'director' => 'Todd Phillips',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Avengers: Endgame',
                'description' => 'The Avengers assemble to reverse the damage caused by Thanos.',
                'poster_url' => 'https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SY679_.jpg',
                'genre' => 'Action',
                'release_year' => 2019,
                'director' => 'Anthony and Joe Russo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Titanic',
                'description' => 'A young couple from different classes fall in love on the ill-fated ship.',
                'poster_url' => 'https://images-cdn.ubuy.co.id/634e36686f87062ff57e6463-titanic-movie-poster-2-sided-original.jpg',
                'genre' => 'Romance',
                'release_year' => 1997,
                'director' => 'James Cameron',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Whiplash',
                'description' => 'A young drummer pushes his limits under a ruthless instructor.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIZQYke1hgTSW5mwGD7Ihggs20mD3Rg7rj7w&s',
                'genre' => 'Drama',
                'release_year' => 2014,
                'director' => 'Damien Chazelle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Her',
                'description' => 'A lonely man falls in love with an AI operating system.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3YIAtXdAbbo3qzNcOkMHj_wgRSkMERDYGEg&s',
                'genre' => 'Romance',
                'release_year' => 2013,
                'director' => 'Spike Jonze',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Grand Budapest Hotel',
                'description' => 'A legendary concierge gets involved in a murder mystery.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2MTMEcy4vObeAp-O--c7tShFgon6U3ncN1w&s',
                'genre' => 'Comedy',
                'release_year' => 2014,
                'director' => 'Wes Anderson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Social Network',
                'description' => 'The founding of Facebook and the drama behind it.',
                'poster_url' => 'https://i.etsystatic.com/6285100/r/il/49d503/2435521859/il_570xN.2435521859_jupb.jpg',
                'genre' => 'Drama',
                'release_year' => 2010,
                'director' => 'David Fincher',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'title' => 'Goodfellas',
                'description' => 'The story of Henry Hill and his life in the mob.',
                'poster_url' => 'https://i.ebayimg.com/images/g/0pwAAOSwxg5X0cf-/s-l400.jpg',
                'genre' => 'Crime',
                'release_year' => 1990,
                'director' => 'Martin Scorsese',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Gladiator',
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor.',
                'poster_url' => 'https://www.movieposters.com/cdn/shop/files/Gladiator.mpw.102813_480x.progressive.jpg?v=1707500493',
                'genre' => 'Action',
                'release_year' => 2000,
                'director' => 'Ridley Scott',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Silence of the Lambs',
                'description' => 'A young FBI cadet must confide in an incarcerated killer to catch another killer.',
                'poster_url' => 'https://www.originalfilmart.com/cdn/shop/products/silence_of_the_lambs_1991_australian_original_film_art_1200x.jpg?v=1585313042',
                'genre' => 'Thriller',
                'release_year' => 1991,
                'director' => 'Jonathan Demme',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Se7en',
                'description' => 'Two detectives hunt a serial killer who uses the seven deadly sins.',
                'poster_url' => 'https://www.movieposters.com/cdn/shop/products/248875c05ff4754eb10c861c0f21c42d_5be29f59-c841-4941-ae55-3dff98e364dc_480x.progressive.jpg?v=1573585329',
                'genre' => 'Thriller',
                'release_year' => 1995,
                'director' => 'David Fincher',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Green Mile',
                'description' => 'The lives of guards on Death Row are affected by one of their charges.',
                'poster_url' => 'https://f.media-amazon.com/images/I/51mvJdnlXrL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
                'genre' => 'Drama',
                'release_year' => 1999,
                'director' => 'Frank Darabont',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Saving Private Ryan',
                'description' => 'Following the Normandy Landings, a group of soldiers go behind enemy lines.',
                'poster_url' => 'https://www.movieposters.com/cdn/shop/products/b4c809b14aec6fefd9a19781b56cf8d4_6028b54a-5ca4-4ab3-ad27-2e2c025806d0_480x.progressive.jpg?v=1573655129',
                'genre' => 'War',
                'release_year' => 1998,
                'director' => 'Steven Spielberg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Prestige',
                'description' => 'Two stage magicians engage in a battle to create the ultimate illusion.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREqXDLzShJMcrhnWaRYjUNHfaqq7Jp1vtR1Q&s',
                'genre' => 'Drama',
                'release_year' => 2006,
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Departed',
                'description' => 'An undercover cop and a mole in the police attempt to identify each other.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3jWwmr3zSO-wSFUD3u6lqkMrojzQQdTHSrg&s',
                'genre' => 'Crime',
                'release_year' => 2006,
                'director' => 'Martin Scorsese',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Django Unchained',
                'description' => 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife.',
                'poster_url' => 'https://originalvintagemovieposters.com/wp-content/uploads/2020/05/Django-5980-scaled-687x1024.jpg',
                'genre' => 'Action',
                'release_year' => 2012,
                'director' => 'Quentin Tarantino',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Wolf of Wall Street',
                'description' => 'Based on the true story of Jordan Belfort, a stockbroker who defrauded investors.',
                'poster_url' => 'https://www.movieposters.com/cdn/shop/files/wolfofwallstreet.24x36_480x.progressive.jpg?v=1707502909',
                'genre' => 'Comedy',
                'release_year' => 2013,
                'director' => 'Martin Scorsese',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Mad Max: Fury Road',
                'description' => 'In a post-apocalyptic wasteland, Max teams up with a mysterious woman.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7qyYtjjwVM0UuvweASeEFkekDgIsgJgOTxQ&s',
                'genre' => 'Action',
                'release_year' => 2015,
                'director' => 'George Miller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black Panther',
                'description' => 'T’Challa returns home to the African nation of Wakanda to take his rightful place as king.',
                'poster_url' => 'https://imgc.allpostersimages.com/img/posters/marvel-cinematic-universe-black-panther-shuri-one-sheet-premium-poster_u-L-F9KM8S0.jpg',
                'genre' => 'Action',
                'release_year' => 2018,
                'director' => 'Ryan Coogler',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'title' => 'Up',
                'description' => 'An old man and a young boy embark on an adventure in a flying house.',
                'poster_url' => 'https://m.media-amazon.com/images/M/MV5BNmI1ZTc5MWMtMDYyOS00ZDc2LTkzOTAtNjQ4NWIxNjYyNDgzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                'genre' => 'Animation',
                'release_year' => 2009,
                'director' => 'Pete Docter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'WALL·E',
                'description' => 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey.',
                'poster_url' => 'https://www.movieposters.com/cdn/shop/files/walle.24x36_480x.progressive.jpg?v=1707503166',
                'genre' => 'Animation',
                'release_year' => 2008,
                'director' => 'Andrew Stanton',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inside Out',
                'description' => 'After young Riley is uprooted from her life, her emotions conflict on how to navigate a new city.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsOChzbAVxomR8C_1Lwz_wrlssxRFd_lVWtA&s',
                'genre' => 'Animation',
                'release_year' => 2015,
                'director' => 'Pete Docter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Toy Story',
                'description' => 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy.',
                'poster_url' => 'https://i.ebayimg.com/images/g/140AAOSwSRZe9CRC/s-l1200.jpg',
                'genre' => 'Animation',
                'release_year' => 1995,
                'director' => 'John Lasseter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Finding Nemo',
                'description' => 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2uMGZUCQmYvPmRacjnBRgIQU1N17vYCVQUg&s',
                'genre' => 'Animation',
                'release_year' => 2003,
                'director' => 'Andrew Stanton',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Coco',
                'description' => 'Aspiring musician Miguel, confronted with his family’s ancestral ban on music, enters the Land of the Dead.',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTVZAKKfalmsRh_5gnyRhJenMp0IiAEb1RkQ&s',
                'genre' => 'Animation',
                'release_year' => 2017,
                'director' => 'Lee Unkrich',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}