name: Build and deploy Laravel app to Azure Web App - movie-suggestor

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, mysql, pdo, tokenizer, xml, ctype, json
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Laravel APP_KEY
        run: php artisan key:generate

      - name: Laravel config & route caching
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Zip files for deployment
        run: zip -r release.zip . -x "vendor/*" "node_modules/*" ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E8A2D250A7946BDBA6EC9C58AB25452 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_586B587435324E64A7A991CCB09DC3D0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_126CA76DDC9F4EFBB3949C14E5A06DF9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movie-suggestor'
          slot-name: 'Production'
          package: .
